// frameworks/react/src/ConnectFour.jsx
import { useState } from "react";

import {
    COLUMNS,
    ROWS,
    createBoard,
    currentPlayer,
    drop,
    isColumnFull,
    winner,
} from "./board";

export default function ConnectFour() {
    const [board, setBoard] = useState(createBoard);
    const [moves, setMoves] = useState(0);

    const champion = winner(board);
    const over = Boolean(champion) || moves === ROWS * COLUMNS;

    function play(column) {
        if (over || isColumnFull(board, column)) {
            return;
        }
        setBoard(drop(board, column, currentPlayer(moves)));
        setMoves(moves + 1);
    }

    function reset() {
        setBoard(createBoard());
        setMoves(0);
    }

    return (
        <section className="game">
            <h1>Connect Four</h1>

            <p role="status">
                {champion
                    ? `Player ${champion} wins!`
                    : over
                    ? "It's a tie!"
                    : `Player ${currentPlayer(moves)}, choose a column.`}
            </p>

            <table className="board">
                <tbody>
                    {[...board].reverse().map((cells, rowIndex) => (
                        <tr key={rowIndex}>
                            {cells.map((cell, columnIndex) => (
                                <td key={columnIndex} className={`cell cell--${cell.toLowerCase()}`}>
                                    {cell}
                                </td>
                            ))}
                        </tr>
                    ))}
                </tbody>
            </table>

            <div className="columns">
                {Array.from({ length: COLUMNS }, (_, index) => (
                    <button
                        key={index}
                        type="button"
                        onClick={() => play(index)}
                        disabled={over || isColumnFull(board, index)}
                    >
                        {index + 1}
                    </button>
                ))}
            </div>

            <button type="button" className="reset" onClick={reset}>
                New game
            </button>
        </section>
    );
}

// frameworks/vue/src/components/ConnectFour.vue
<script setup>
import { useConnectFour } from "../composables/useConnectFour";

const { board, over, status, columns, play, reset, isColumnFull } = useConnectFour();
</script>

<template>
    <section class="game">
        <h1>Connect Four</h1>

        <p role="status">{{ status }}</p>

        <table class="board">
            <tbody>
                <tr v-for="(cells, rowIndex) in [...board].reverse()" :key="rowIndex">
                    <td
                        v-for="(cell, columnIndex) in cells"
                        :key="columnIndex"
                        class="cell"
                        :class="`cell--${cell.toLowerCase()}`">
                        {{ cell }}
                    </td>
                </tr>
            </tbody>
        </table>

        <div class="columns">
            <button
                v-for="column in columns"
                :key="column"
                type="button"
                :disabled="over || isColumnFull(board, column)"
                @click="play(column)">
                {{ column + 1 }}
            </button>
        </div>

        <button type="button" @click="reset">New game</button>
    </section>
</template>
